name: Build web player

on:
  push:
    branches:
      - "web-build-test"

jobs:
  buildWebPlayer:
    name: Build for WebGL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Blocktest/Library
          key: Library-WebGL
          restore-keys: Library-

      - name: Setup license
        env:
          LICENSE_FILE_PATH: ./.github/License.ulf
        run: |
          echo 'UNITY_LICENSE<<LICENSE-EOF' >> "$GITHUB_ENV"
          cat "$LICENSE_FILE_PATH" >> "$GITHUB_ENV"
          printf "\nLICENSE-EOF" >> "$GITHUB_ENV"

      - uses: game-ci/unity-builder@v2
        id: build
        with:
          unityVersion: 2020.2.5f1
          projectPath: Blocktest
          targetPlatform: WebGL

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: gh-pages
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          FOLDER: build/WebGL
